#!/usr/bin/env python3
"""
Test to demonstrate trigger timing issue and fix.
Shows how simultaneous triggers should be emitted together.
"""

print("\n" + "="*70)
print("SIMULTANEOUS TRIGGER TIMING TEST")
print("="*70)

print("\n[PROBLEM: Separated triggers]")
print("-" * 70)
print("BANSHEE's dagger finds LYSSARA STARFORGED's flank!")
print("The edge bites deep and draws crimson!")
print("* LYSSARA STARFORGED switches to strategy 2")
print("  [Trigger: 'When you have taken heavy damage']")
print("")
print("A dog runs loose in the upper tier!")
print("")
print("LYSSARA STARFORGED unleashes a ceaseless, crushing barrage...")
print("LYSSARA STARFORGED attacks relentlessly at BANSHEE's midsection...")
print("")
print("BANSHEE keeps his feet light and ready!")
print("* BANSHEE switches to strategy 3  <-- DELAYED!")
print("  [Trigger: 'When your foe has taken heavy damage']")
print("")
print("Issue: Both triggers evaluated the SAME damage event")
print("(LYSSARA taking heavy damage), so both should emit together")
print("at the moment the damage was dealt.")

print("\n[SOLUTION: Simultaneous triggers]")
print("-" * 70)
print("BANSHEE's dagger finds LYSSARA STARFORGED's flank!")
print("The edge bites deep and draws crimson!")
print("* LYSSARA STARFORGED switches to strategy 2")
print("  [Trigger: 'When you have taken heavy damage']")
print("* BANSHEE switches to strategy 3")
print("  [Trigger: 'When your foe has taken heavy damage']")
print("")
print("A dog runs loose in the upper tier!")
print("")
print("LYSSARA STARFORGED unleashes a ceaseless, crushing barrage...")
print("")
print("Correct: Both strategy switches happen immediately after the")
print("damage is dealt and HP is updated, before any other narrative.")

print("\n[HOW TO FIX]")
print("-" * 70)
print("In _resolve_action (lines 3325-3326), both strategy checks")
print("should happen sequentially and both emit their switches")
print("before any other narrative text (low-HP commentary, etc).")
print("")
print("Current code:")
print("  self._check_defender_strategy_only(ds_, as_, minute)  # Line 3325")
print("  self._check_defender_strategy_only(as_, ds_, minute)  # Line 3326")
print("  # Low-HP status commentary (line 3328+)")
print("")
print("This IS correct - both should emit before other text.")
print("If they're not, the issue might be:")
print("1. Strategy triggers aren't evaluating foe HP correctly")
print("2. Strategy switches are happening but not emitting")
print("3. Crowd text or other narrative is being inserted")
print("   at the wrong point in the emit sequence")

print("\n" + "="*70 + "\n")
